CRUDDemo/CRUDDemo/Controllers/PersonsController.cs
using Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ServiceContract;
using ServiceContract.DTO;
using ServiceContract.Enums;
using Services;

namespace CRUDDemo.Controllers
{
    [Route("[controller]")]
    public class PersonsController : Controller
    {
        private IPersonService _personService;
        private readonly ICountryService _countryService;
        public PersonsController(IPersonService personService, ICountryService countryService)
        {
            _personService = personService;
            _countryService = countryService;

        }

        [Route("[action]")]
        [Route("/")]
        public IActionResult Index(string searchBy, string? searchString, string sortBy = nameof(PersonResponseDTO.PersonName), SortOrderOptions sortOrder = SortOrderOptions.ASC)
        {
            ViewData["SearchFields"] = new Dictionary<string, string>()
            {
                 
                  { nameof(PersonResponseDTO.PersonName), "Person Name" },
                  { nameof(PersonResponseDTO.Email), "Email" },
                  { nameof(PersonResponseDTO.DateOfBirth), "Date of Birth" },
                  { nameof(PersonResponseDTO.Gender), "Gender" },
                  { nameof(PersonResponseDTO.CountryID), "Country" },
                  { nameof(PersonResponseDTO.Address), "Address" }
            };
            var filterdPersons = _personService.GetFilteredPersons(searchBy,searchString);
            ViewData["CurrentSearchBy"] = searchBy;    
            ViewData["CurrentSearchString"] = searchString;
            var sortedPersons = _personService.GetSortedPersons(filterdPersons, sortBy, sortOrder);
            ViewBag.CurrentSortBy = sortBy;
            ViewBag.CurrentSortOrder = sortOrder.ToString();
            return View(sortedPersons);
        }

        [HttpGet]
        [Route("[action]")]
        public IActionResult Create()
        {
            var countries=_countryService.GetAllCountries();
            ViewBag.Countries = countries.Select(c=>new SelectListItem() { Text=c.CountryName,Value=c.CountryId.ToString()});
            return View();
        }
        [HttpPost]
        [Route("[action]")]
        public IActionResult Create(PersonAddDTO personAddDTO)
        {
            if (!ModelState.IsValid)
            {
                var countries = _countryService.GetAllCountries();
                ViewBag.Countries = countries.Select(c => new SelectListItem() { Text = c.CountryName, Value = c.CountryId.ToString() });
                ViewBag.Errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList();
                return View(personAddDTO);
            }

            PersonResponseDTO? persons =_personService.AddPerson(personAddDTO);
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("[action]/{personId}")]
        public IActionResult Edit(Guid personId)
        {
            PersonResponseDTO? personResponseDTO=_personService.GetPersonById(personId);
            if (personResponseDTO == null)
            {
                return RedirectToAction(nameof(Index));
            }
            var countries = _countryService.GetAllCountries();
            ViewBag.Countries = countries.Select(c => new SelectListItem() { Text = c.CountryName, Value = c.CountryId.ToString() });
            return View(personResponseDTO.ToPersonUpdateRequest());
        }
        [HttpPost]
        [Route("[action]/{personId}")]
        public IActionResult Edit(PersonUpdateDTO personUpdateDTO)
        {
            if(!ModelState.IsValid)
            {
                var countries = _countryService.GetAllCountries();
                ViewBag.Countries = countries.Select(c => new SelectListItem() { Text = c.CountryName, Value = c.CountryId.ToString() });
                ViewBag.Errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList();
               
                return View(personUpdateDTO);
            }
            PersonResponseDTO? personResponseDTO = _personService.GetPersonById(personUpdateDTO.PersonID);
            if (personResponseDTO == null)
            {
                return RedirectToAction(nameof(Index));
            }
            _personService.UpdatePerson(personUpdateDTO);

            return RedirectToAction(nameof(Index));

        }

        [HttpGet]
        [Route("[action]/{personId}")]
        public IActionResult Delete(Guid personId)
        {
            PersonResponseDTO? person=_personService.GetPersonById(personId);
            if (person == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return View(person);
        }

        [HttpPost]
        [Route("[action]/{personId}")]
        public IActionResult Delete(PersonUpdateDTO personUpdateDTO )
        {
            PersonResponseDTO? person = _personService.GetPersonById(personUpdateDTO.PersonID);
            if (person == null)
            {
                return RedirectToAction(nameof(Index));
            }
            _personService.DeletePerson(personUpdateDTO.PersonID);
            return RedirectToAction(nameof(Index));
        }
    } 
}

CRUDDemo/CRUDDemo/Views/Persons/Create.cshtml
@model PersonResponseDTO
﻿@{
    ViewBag.Title = "Create Person";
}

<a asp-controller="Persons" asp-action="Index" class="link-hover">Back to Persons List</a>
<h2>Create Person</h2>

<div class="w-50">
    <form asp-controller="Persons" asp-action="Create"  method="post">

        @*PersonName*@
        <div class="form-field flex">
            <div class="w-25">
                <label asp-for="PersonName" class="form-label pt">Person Name</label>
            </div>
            <div class="flex-1">
                <input asp-for="PersonName" type="text" class="form-input" />
                <span asp-validation-for="PersonName"></span>
            </div>
        </div>


        @*Email*@
        <div class="form-field flex">
            <div class="w-25">
                <label asp-for="Email" class="form-label pt">Email</label>
            </div>
            <div class="flex-1">
                <input type="email" asp-for="Email" class="form-input" />
                <span asp-validation-for="Email"></span>
            </div>
        </div>

        @*DateOfBirth*@
        <div class="form-field flex">
            <div class="w-25">
                <label asp-for="DateOfBirth" class="form-label pt">Date of Birth</label>
            </div>
            <div class="flex-1">
                <input type="date" asp-for="DateOfBirth" class="form-input" />
                <span asp-validation-for="DateOfBirth"></span>
            </div>
        </div>

        @*Gender*@
        <div class="form-field flex">
            <div class="w-25">
                <label class="form-label">Gender</label>
            </div>
            @{
                string[] genders = Enum.GetNames(typeof(GenderOptions));
            }
            <div class="flex-1">
                @foreach(string gender in genders)
                {
                    <input type="radio" asp-for="Gender" value="@gender" />
                    <label asp-for="Gender">Male</label>
                    <span asp-validation-for="Gender"></span>
                }
      
            </div>
        </div>

        @*Country*@
        <div class="form-field flex">
            <div class="w-25">
                <label class="form-label" for="CountryID">Country</label>
            </div>
            <div class="flex-1">
                <select asp-items="@ViewBag.Countries" class="form-input">
                    <option value="">Please Select</option>
                </select>
                <span asp-validation-for="Country"></span>
            </div>
        </div>


        @*Address*@
        <div class="form-field flex">
            <div class="w-25">
                <label asp-for="Address" class="form-label pt">Address</label>
            </div>
            <div class="flex-1">
                <textarea asp-for="Address" class="form-input"></textarea>
                <span asp-validation-for="Address"></span>
            </div>
        </div>

        @*ReceiveNewsLetters*@
        <div class="form-field flex">
            <div class="w-25">
            </div>
            <div class="flex-1">
                <input type="checkbox" asp-for="ReceiveNewsLetters" value="true" />
                <label asp-for="ReceiveNewsLetters" class="form-label">Receive News Letters</label>
                <span asp-validation-for="ReceiveNewsLetters"></span>
            </div>
        </div>

        @*Submit*@
        <div class="form-field flex">
            <div class="w-25">
            </div>
            <div class="flex-1">
                <button class="button button-green-back">Create</button>

                @if (ViewBag.Errors != null)
                {
                    <div class="text-red ml">
                        <ul>
                            @foreach (string error in ViewBag.Errors)
                            {
                                <li class="ml">@error</li>
                            }
                        </ul>
                    </div>
                }
            </div>
        </div>

    </form>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" asp-fallback-test="window.jQuery" asp-fallback-src="~/jquery.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.4/jquery.validate.min.js" asp-fallback-test="window.jQuery.validator" asp-fallback-src="~/jquery.validate.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js" asp-fallback-test="window.jQuery.validator.unobstrusive" asp-fallback-src="~/jquery.validate.unobtrusive.min.js"></script>

CRUDDemo/CRUDDemo/Views/Persons/Delete.cshtml
@model PersonResponseDTO
@{
    ViewBag.Title = "Delete Person";
}

<a asp-controller="Persons" asp-action="Index" class="link-hover">Back to Persons List</a>
<h2>Delete Person</h2>
<h3>Are you sure to delete this person?</h3>

<div class="center-box">
    <form asp-controller="Persons" asp-action="Delete" method="post">

        <input type="hidden" asp-for="PersonID" />

        @*PersonName*@
        <div class="form-field flex">
            <div class="w-25">
                <label asp-for="PersonName" class="form-label pt">Person Name</label>
            </div>
            <div class="flex-1">
                <input asp-for="PersonName" class="form-input" disabled="disabled" />
                <span asp-validation-for="PersonName" class="text-red"></span>
            </div>
        </div>


        @*Email*@
        <div class="form-field flex">
            <div class="w-25">
                <label asp-for="Email" class="form-label pt">Email</label>
            </div>
            <div class="flex-1">
                <input asp-for="Email" class="form-input" disabled="disabled" />
                <span asp-validation-for="Email" class="text-red"></span>
            </div>
        </div>


        @*Submit*@
        <div class="form-field flex">
            <div class="w-25">
            </div>
            <div class="flex-1">
                <button class="button button-red-back">Delete</button>

                <div asp-validation-summary="All" class="text-red"></div>

                @if (ViewBag.Errors != null)
                {
                    <div class="text-red ml">
                        <ul>
                            @foreach (string error in ViewBag.Errors)
                            {
                                <li class="ml">@error</li>
                            }
                        </ul>
                    </div>
                }
            </div>
        </div>

    </form>
</div>

CRUDDemo/CRUDDemo/Views/Persons/Edit.cshtml
@model PersonUpdateDTO
﻿@{
    ViewBag.Title = "Update Person";
}

<a asp-controller="Persons" asp-action="Index" class="link-hover">Back to Persons List</a>
<h2>Edit Person</h2>

<div class="center-box">
    <form asp-controller="Persons" asp-action="Edit" method="post">

        <input type="hidden" asp-for="PersonID" />

        @*PersonName*@
        <div class="form-field flex">
            <div class="w-25">
                <label asp-for="PersonName" class="form-label pt">Person Name</label>
            </div>
            <div class="flex-1">
                <input asp-for="PersonName" class="form-input" />
                <span asp-validation-for="PersonName" class="text-red"></span>
            </div>
        </div>


        @*Email*@
        <div class="form-field flex">
            <div class="w-25">
                <label asp-for="Email" class="form-label pt">Email</label>
            </div>
            <div class="flex-1">
                <input asp-for="Email" class="form-input" />
                <span asp-validation-for="Email" class="text-red"></span>
            </div>
        </div>

        @*DateOfBirth*@
        <div class="form-field flex">
            <div class="w-25">
                <label asp-for="DateOfBirth" class="form-label pt">Date of Birth</label>
            </div>
            <div class="flex-1">
                <input asp-for="DateOfBirth" class="form-input" />
                <span asp-validation-for="DateOfBirth" class="text-red"></span>
            </div>
        </div>

        @*Gender*@
        <div class="form-field flex">
            <div class="w-25">
                <label class="form-label">Gender</label>
            </div>
            <div class="flex-1">
                @{
                    string[] genders = (string[])Enum.GetNames(typeof(GenderOptions));
                }
                @foreach (string gender in genders)
                {
                    <input type="radio" asp-for="Gender" value="@gender" />
                    <label for="@gender">@gender</label>
                }
                <span asp-validation-for="Gender" class="text-red"></span>
            </div>
        </div>

        @*Country*@
        <div class="form-field flex">
            <div class="w-25">
                <label class="form-label" asp-for="CountryID">Country</label>
            </div>
            <div class="flex-1">
                <select asp-for="CountryID" class="form-input" asp-items="@ViewBag.Countries">
                    <option value="">Please Select</option>
                </select>
                <span asp-validation-for="CountryID" class="text-red"></span>
            </div>
        </div>


        @*Address*@
        <div class="form-field flex">
            <div class="w-25">
                <label asp-for="Address" class="form-label pt">Address</label>
            </div>
            <div class="flex-1">
                <textarea asp-for="Address" class="form-input"></textarea>
                <span asp-validation-for="Address" class="text-red"></span>
            </div>
        </div>

        @*ReceiveNewsLetters*@
        <div class="form-field flex">
            <div class="w-25">
            </div>
            <div class="flex-1">
                <input asp-for="ReceiveNewsLetters" value="true" />
                <label asp-for="ReceiveNewsLetters" class="form-label">Receive News Letters</label>
                <span asp-validation-for="ReceiveNewsLetters" class="text-red"></span>
            </div>
        </div>

        @*Submit*@
        <div class="form-field flex">
            <div class="w-25">
            </div>
            <div class="flex-1">
                <button class="button button-green-back">Update</button>

                <div asp-validation-summary="All" class="text-red"></div>

                @if (ViewBag.Errors != null)
                {
                    <div class="text-red ml">
                        <ul>
                            @foreach (string error in ViewBag.Errors)
                            {
                                <li class="ml">@error</li>
                            }
                        </ul>
                    </div>
                }
            </div>
        </div>

    </form>
</div>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" asp-fallback-test="window.jQuery" asp-fallback-src="~/jquery.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.4/jquery.validate.min.js" asp-fallback-test="window.jQuery.validator" asp-fallback-src="~/jquery.validate.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js" asp-fallback-test="window.jQuery.validator.unobstrusive" asp-fallback-src="~/jquery.validate.unobtrusive.min.js"></script>

CRUDDemo/CRUDDemo/Views/Persons/Index.cshtml
@using ServiceContract.DTO;
@using ServiceContract.Enums;
@model IEnumerable<PersonResponseDTO>
<form action="~/persons/index" method="get">
    <h1>Persons</h1>

    <div class="box flex">
        <div class="flex-1">
            <select class="form-input" name="searchBy">
                @foreach (var field in ViewBag.SearchFields)
                {
                    if (field.Key == ViewBag.CurrentSearchBy)
                    {
                        <option value="@field.Key" selected="selected">@field.Value</option>
                    }
                    else
                    {
                        <option value="@field.Key">@field.Value</option>
                    }

                }

            </select>
        </div>

        <div class="flex-1">
            <input type="search" id="Search" class="form-input" placeholder="Search" name="searchString" value="@ViewBag.CurrentSearchString" />
        </div>

        <div class="flex-1">
            <button class="button button-blue-back">Search</button>
            <a href="~/persons/index" class="link-hover">Clear all</a>
        </div>
    </div>


    <table class="table w-100 mt">
        <thead>
            <tr>
                <th>
                    @await Html.PartialAsync("_GridColumnPartial", new ViewDataDictionary(ViewData) {
                    { "ColumnName", nameof(PersonResponseDTO.PersonName) },
                    { "DisplayName", "Person Name" },
                    })
                </th>
                <th>
                    @await Html.PartialAsync("_GridColumnPartial", new ViewDataDictionary(ViewData) {
                    { "ColumnName", nameof(PersonResponseDTO.Email) },
                    { "DisplayName", "Email" },
                    })
                </th>
                <th>
                    @await Html.PartialAsync("_GridColumnPartial", new ViewDataDictionary(ViewData) {
                    { "ColumnName", nameof(PersonResponseDTO.DateOfBirth) },
                    { "DisplayName", "Date of Birth" },
                    })
                </th>
                <th>
                    @await Html.PartialAsync("_GridColumnPartial", new ViewDataDictionary(ViewData) {
                    { "ColumnName", nameof(PersonResponseDTO.Age) },
                    { "DisplayName", "Age" },
                    })
                </th>
                <th>
                    @await Html.PartialAsync("_GridColumnPartial", new ViewDataDictionary(ViewData) {
                    { "ColumnName", nameof(PersonResponseDTO.Gender) },
                    { "DisplayName", "Gender" },
                    })
                </th>
                <th>
                    @await Html.PartialAsync("_GridColumnPartial", new ViewDataDictionary(ViewData) {
                    { "ColumnName", nameof(PersonResponseDTO.Country) },
                    { "DisplayName", "Country" },
                    })
                </th>
                <th>
                    @await Html.PartialAsync("_GridColumnPartial", new ViewDataDictionary(ViewData) {
                    { "ColumnName", nameof(PersonResponseDTO.Address) },
                    { "DisplayName", "Address" },
                    })
                </th>
                <th>
                    @await Html.PartialAsync("_GridColumnPartial", new ViewDataDictionary(ViewData) {
                    { "ColumnName", nameof(PersonResponseDTO.ReceiveNewsLetters) },
                    { "DisplayName", "Receive News Letters" },
                    })
                </th>
                <th>
                    Options
                </th>

            </tr>
        </thead>
        <tbody>
            @foreach (PersonResponseDTO person in Model)
            {
                <tr>
                    <td>@person.PersonName</td>
                    <td>@person.Email</td>
                    <td>@person.DateOfBirth?.ToString("dd MMM yyyy")</td>
                    <td>@person.Age</td>
                    <td>@person.Gender</td>
                    <td>@person.Country</td>
                    <td>@person.Address</td>
                    <td>@person.ReceiveNewsLetters</td>
                    <td >
                        <a asp-controller="Persons" asp-action="Edit" asp-route-personID="@person.PersonID">Edit</a>
                        @* /Persons/Edit/1 *@

                        <a asp-controller="Persons" asp-action="Delete" asp-route-personID="@person.PersonID">Delete</a>
                        @* /Persons/Delete/1 *@
                    </td>
                </tr>
            }
            <tr></tr>
        </tbody>

    </table>
</form>

CRUDDemo/CRUDDemo/Views/Shared/_GridColumnPartial.cshtml
@if (ViewBag.CurrentSortBy == ViewBag.ColumnName && ViewBag.CurrentSortOrder == SortOrderOptions.ASC.ToString())
{
    <a href="~/Persons/Index?searchBy=@ViewBag.CurrentSearchBy&searchString=@ViewBag.CurrentSearchString&sortBy=@ViewBag.ColumnName&sortOrder=DESC">@ViewBag.DisplayName</a>
}
else if (ViewBag.CurrentSortBy == ViewBag.ColumnName && ViewBag.CurrentSortOrder == SortOrderOptions.DESC.ToString())
{
    <a href="~/Persons/Index?searchBy=@ViewBag.CurrentSearchBy&searchString=@ViewBag.CurrentSearchString&sortBy=@ViewBag.ColumnName&sortOrder=ASC">@ViewBag.DisplayName</a>
}
else@*  (ViewBag.CurrentSortBy != ViewBag.ColumnName && ViewBag.CurrentSortOrder == SortOrderOptions.ASC.ToString()) *@
{
    <a href="~/Persons/Index?searchBy=@ViewBag.CurrentSearchBy&searchString=@ViewBag.CurrentSearchString&sortBy=@ViewBag.ColumnName&sortOrder=ASC">@ViewBag.DisplayName</a>
}

CRUDDemo/CRUDDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Stylesheet.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />s
</head>
<body>
    <div class="container">
        <div class="navbar">
            <div class="navbar-brand">CRUD Demo</div>
            <ul>
                <li>
                    <a href="~/persons/index">Persons</a>
                </li>
            </ul>
        </div>

        <div class="page-content">
            @RenderBody()
        </div>
    </div>
</body>
</html>